enable clang

diff --git a/RUNME b/RUNME
--- a/RUNME
+++ b/RUNME
@@ -46,8 +46,26 @@ cp README.md.template README.md
 for i in $SUBDIRS
 do
     echo
-  log $i:
-    (cd $i; sh ./RUNME; ./example) | sed 's/^/    /g'
+    echo
+    echo
+    echo
+    echo
+    echo
+    log $i:
+    log "================================================="
+    cd $i
+    sh ./RUNME;
+    if [ $? -ne 0 ]; then
+      log_err "failed"
+      exit 1
+    fi
+    if [ ! -f example ]; then
+      log_err "build failed"
+      exit 1
+    fi
+    ./example
+    cd ..
+
     # Makes the main page too long:
     # cat $i/README.md >> README.md
 done
diff --git a/common/RUNME b/common/RUNME
--- a/common/RUNME
+++ b/common/RUNME
@@ -1,5 +1,5 @@
 #!/bin/sh
-# 
+#
 # Copyright (C) 2014 Neil McGill
 #
 # This software is free software; you can redistribute it and/or
@@ -24,7 +24,7 @@ cat Makefile.base | sed '/DO NOT DELETE/,$d' > Makefile.tmp
 mv Makefile.tmp Makefile
 makedepend *.cpp -p .o/ 2>/dev/null
 
-echo "COMPILER_FLAGS=-std=c++2a -Werror -g -ggdb3 # AUTOGEN" > .Makefile
+echo "COMPILER_FLAGS=-std=c++2a -Werror -g -O3 -fstack-protector-all -ggdb3 # AUTOGEN" > .Makefile
 echo "    " >> .Makefile
 echo "CLANG_COMPILER_WARNINGS=-Wall # AUTOGEN" >> .Makefile
 echo "GCC_COMPILER_WARNINGS=-Wall # AUTOGEN" >> .Makefile
@@ -36,10 +36,10 @@ then
     echo "COMPILER_WARNINGS=\$(GCC_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
     echo "COMPILER_WARNINGS=\$(GXX_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
     echo "COMPILER_WARNINGS=\$(CLANG_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
-    echo "CC=clang # AUTOGEN" >> .Makefile
-    echo "# CC=gcc # AUTOGEN" >> .Makefile
-    echo "# CC=cc # AUTOGEN" >> .Makefile
-    echo "# CC=g++ # AUTOGEN" >> .Makefile
+    echo "CXX=clang # AUTOGEN" >> .Makefile
+    echo "# CXX=gcc # AUTOGEN" >> .Makefile
+    echo "# CXX=cc # AUTOGEN" >> .Makefile
+    echo "# CXX=g++ # AUTOGEN" >> .Makefile
 else
     `gcc --version >/dev/null 2>/dev/null`
     if [ $? -eq 0 ]
@@ -47,36 +47,35 @@ else
         echo "COMPILER_WARNINGS=\$(CLANG_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
         echo "COMPILER_WARNINGS=\$(GXX_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
         echo "COMPILER_WARNINGS=\$(GCC_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
-	echo "# CC=clang # AUTOGEN" >> .Makefile
-	echo "CC=gcc # AUTOGEN" >> .Makefile
-	echo "# CC=cc # AUTOGEN" >> .Makefile
-	echo "# CC=g++ # AUTOGEN" >> .Makefile
+        echo "# CXX=clang # AUTOGEN" >> .Makefile
+        echo "CXX=gcc # AUTOGEN" >> .Makefile
+        echo "# CXX=cc # AUTOGEN" >> .Makefile
+        echo "# CXX=g++ # AUTOGEN" >> .Makefile
     else
-	`g++ --version >/dev/null 2>/dev/null`
-	if [ $? -eq 0 ]
-	then
+        `g++ --version >/dev/null 2>/dev/null`
+        if [ $? -eq 0 ]
+        then
             echo "COMPILER_WARNINGS=\$(CLANG_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
             echo "COMPILER_WARNINGS=\$(GCC_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
             echo "COMPILER_WARNINGS=\$(GXX_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
-	    echo "# CC=clang # AUTOGEN" >> .Makefile
-	    echo "# CC=gcc # AUTOGEN" >> .Makefile
-	    echo "# CC=cc # AUTOGEN" >> .Makefile
-	    echo "CC=g++ # AUTOGEN" >> .Makefile
-	else
+            echo "# CXX=clang # AUTOGEN" >> .Makefile
+            echo "# CXX=gcc # AUTOGEN" >> .Makefile
+            echo "# CXX=cc # AUTOGEN" >> .Makefile
+            echo "CXX=g++ # AUTOGEN" >> .Makefile
+        else
             echo "COMPILER_WARNINGS=\$(CLANG_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
             echo "COMPILER_WARNINGS=\$(GXX_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
             echo "COMPILER_WARNINGS=\$(GCC_COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
-	    echo "# CC=clang # AUTOGEN" >> .Makefile
-	    echo "# CC=gcc # AUTOGEN" >> .Makefile
-	    echo "# CC=cc # AUTOGEN" >> .Makefile
-	    echo "CC=g++ # AUTOGEN" >> .Makefile
-	fi
+            echo "# CXX=clang # AUTOGEN" >> .Makefile
+            echo "# CXX=gcc # AUTOGEN" >> .Makefile
+            echo "# CXX=cc # AUTOGEN" >> .Makefile
+            echo "CXX=g++ # AUTOGEN" >> .Makefile
+        fi
     fi
 fi
 
 echo "    " >> .Makefile
-echo "EXE=$EXE # AUTOGEN" >> .Makefile
-echo "LDLIBS=$LDLIBS # AUTOGEN" >> .Makefile
+echo "LDLIBS+=-lstdc++ # AUTOGEN" >> .Makefile
 echo "CXXFLAGS=\$(COMPILER_FLAGS) \$(COMPILER_WARNINGS) # AUTOGEN" >> .Makefile
 
 cat Makefile | grep -v AUTOGEN | grep -v "^    $" >> .Makefile
@@ -86,26 +85,30 @@ then
     mv .Makefile Makefile
     if [ ! -f Makefile ]
     then
-	log_err "No makefile?!"
-	exit 1
+        log_err "No makefile?!"
+        exit 1
     fi
-else 
+else
     log_err "Makefile create fail?!"
     exit 1
 fi
 
 log_info "Cleaning"
-make clobber | sed 's/^/  /g'
+make clobber
+if [ $? -ne 0 ]; then
+  log_err "make clobber failed"
+  exit 1
+fi
 
 CORES=""
 
 case `uname` in
     *Darwin*)
-	CORES=`/usr/sbin/system_profiler -detailLevel full SPHardwareDataType  | grep Cores | sed 's/.*: //g'`
+        CORES=`/usr/sbin/system_profiler -detailLevel full SPHardwareDataType  | grep Cores | sed 's/.*: //g'`
     ;;
 
     *inux*)
-	CORES=`cat /proc/cpuinfo | grep "cpu cores" | head -1 | awk '{print $4}'`
+        CORES=`cat /proc/cpuinfo | grep "cpu cores" | head -1 | awk '{print $4}'`
     ;;
 esac
 
@@ -115,7 +118,11 @@ then
 fi
 
 log_info "Compiling"
-make $CORES $* all | sed 's/^/  /g'
+make $CORES $* all 
+if [ $? -ne 0 ]; then
+  log_err "make failed"
+  exit 1
+fi
 
 if [ $? -eq 0 ]
 then
